packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "@swc/core": true
  esbuild: true
  msw: true
  prisma: true
  unrs-resolver: true

catalog:
  "@types/node": ^25.6.0
  eslint: ^9.39.4
  shadcn: ^4.3.1
  typescript: ^5.9.3
