export const ResponseCode = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FEATURE_NOT_IMPLEMENTED: 'FEATURE_NOT_IMPLEMENTED',

  // Config sync
  CONFIG_OK: 'CONFIG_OK',

  // Orders
  ORDER_SYNCED: 'ORDER_SYNCED',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_OK: 'ORDER_OK',
  ORDERS_OK: 'ORDERS_OK',
  ORDER_UPDATED: 'ORDER_UPDATED',

  // Restaurants
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_CREATED: 'RESTAURANT_CREATED',
  RESTAURANT_UPDATED: 'RESTAURANT_UPDATED',
  RESTAURANT_OK: 'RESTAURANT_OK',
  RESTAURANTS_OK: 'RESTAURANTS_OK',

  // Platforms
  PLATFORM_UPDATED: 'PLATFORM_UPDATED',
  PLATFORMS_OK: 'PLATFORMS_OK',
  PLATFORM_NOT_FOUND: 'PLATFORM_NOT_FOUND',

  // Credentials
  INSTALLATION_KEY_PROVISIONED: 'INSTALLATION_KEY_PROVISIONED',
  INSTALLATION_KEY_OK: 'INSTALLATION_KEY_OK',
  CREDENTIAL_UPDATED: 'CREDENTIAL_UPDATED',

  // Daily summaries
  SUMMARIES_OK: 'SUMMARIES_OK',

  // Holiday calendar
  HOLIDAY_TYPES_OK: 'HOLIDAY_TYPES_OK',
  HOLIDAY_CALENDAR_OK: 'HOLIDAY_CALENDAR_OK',
  CALENDAR_ENTRY_UPDATED: 'CALENDAR_ENTRY_UPDATED',

  // Holiday policies
  HOLIDAY_POLICIES_OK: 'HOLIDAY_POLICIES_OK',
  HOLIDAY_POLICY_UPDATED: 'HOLIDAY_POLICY_UPDATED',
  HOLIDAY_POLICY_DELETED: 'HOLIDAY_POLICY_DELETED',

  // Working day overrides
  OVERRIDES_OK: 'OVERRIDES_OK',
  OVERRIDE_CREATED: 'OVERRIDE_CREATED',
  OVERRIDE_UPDATED: 'OVERRIDE_UPDATED',
  OVERRIDE_DELETED: 'OVERRIDE_DELETED',
  OVERRIDE_ALREADY_EXISTS: 'OVERRIDE_ALREADY_EXISTS',

  // Schedule preview
  SCHEDULE_PREVIEW_OK: 'SCHEDULE_PREVIEW_OK',
} as const;

export type ResponseCode = (typeof ResponseCode)[keyof typeof ResponseCode];
